apiVersion: apps/v1
kind: Deployment          #start up the deployment, initial set up is one container with 3 pods    
metadata:
  name: flask-deployment
spec:
  replicas: 2            # replace with  'replicas: 5' when scale up from 3 to 5
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: kg0529/flask
        ports:
        - containerPort: 9090

metadata:
  name: flask-new
spec:
  replicas: 1            # replace with  'replicas: 5' when scale up from 3 to 5
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: kg0529/flask
        ports:
        - containerPort: 9090

---
apiVersion: v1
kind: Service           #start up the service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
